# Generated by Django 4.1.5 on 2023-05-19 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="comment",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
