# Generated by Django 4.1.5 on 2023-05-19 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0003_alter_comment_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="user",
            new_name="Comment_username",
        ),
    ]
